 i# Shopify App Configuration
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Upload Lift Pro"
client_id = "b3dfbb5aae7397a26e4073b0196a594e"
application_url = "https://customizerapp.dev"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_customers"

[auth]
redirect_urls = [
  "https://customizerapp.dev/auth/callback"
]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app-uninstalled"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders-create"

[[webhooks.subscriptions]]
topics = [ "orders/paid" ]
uri = "/webhooks/orders-paid"

[[webhooks.subscriptions]]
topics = [ "orders/cancelled" ]
uri = "/webhooks/orders-cancelled"

[[webhooks.subscriptions]]
topics = [ "orders/fulfilled" ]
uri = "/webhooks/orders-fulfilled"

[[webhooks.subscriptions]]
topics = [ "products/update" ]
uri = "/webhooks/products-update"

[[webhooks.subscriptions]]
topics = [ "products/delete" ]
uri = "/webhooks/products-delete"

[app_proxy]
url = "https://customizerapp.dev/api/proxy"
subpath = "customizer"
prefix = "apps"

[pos]
embedded = false

