# Fast DTF Transfer - Shopify App Configuration

client_id = "f122b497901d3db350a2c20b7ce4bc2d"
name = "FDT-Upload"
application_url = "https://customizerapp.dev"
embedded = true
handle = "fast-dtf-transfer"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "fast-dtf-transfer.myshopify.com"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products-delete"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products-update"

[access_scopes]
scopes = "read_products,write_products,read_orders,write_orders,read_files,write_files"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://customizerapp.dev/auth/callback",
  "https://customizerapp.dev/api/auth/callback"
]

[app_proxy]
url = "https://customizerapp.dev"
subpath = "customizer"
prefix = "apps"

[pos]
embedded = false
