# Learn more about configuring your checkout UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

api_version = "2025-10"

[[extensions]]
name = "Upload Design Display"
handle = "checkout-upload-display"
type = "ui_extension"
uid = "75fa9cf3-704b-8be2-29e0-d78cac960accf61b2993"

# Block target - can be placed anywhere in checkout
[[extensions.targeting]]
module = "./src/CheckoutLineItem.jsx"
target = "purchase.checkout.block.render"

# Also show on Thank You page
[[extensions.targeting]]
module = "./src/CheckoutLineItem.jsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
api_access = true
